# Sample config
# Configures Web-app
# Language
language: nodejs
nodejs:
  - stable
require:
  - ruby
name: app
# Command to start
start: node bin/www
port: 8080

global:
  npm:
    - bower
    - grunt-cli
    - nodemon
    - node-gyp
  gem:
    - sass

env:
  - NODE_ENV=dev

build:
  install:
    - npm install
  script:
    - grunt compile

# ENV
# BOSS_LANG_VERSION
# BOSS_OS
# BOSS_RUNNER_VERSION
# BOSS_NODEJS_VERSION
# BOSS_RUBY_VERSION
# BOSS_PYTHON_VERSION
# BOSS_BOX_VERSION
# BOSS_RUN_ID
# BOSS_TUB_ID
# BOSS_APP_NAME
# BOSS_TUB_NAME
