# Sample tub config
# Name of tub (JAKHU_WORKER_NAME)
# The rest is in config
name: default

# Lang
language: nodejs
version: stable

# Web-app dir (JAKHU_WEB_DIR)
dir: vagrant

# Web-app name (JAKHU_APP_NAME)
app: foo
